---
- hosts: all
  vars:
    PROV_CONN: none
  tasks:
  # - name: configure the provisioning network
  #   ansible.builtin.command:
  #     cmd: |
  #       nmcli con down \"{{ PROV_CONN }}\"
  #       nmcli con delete \"{{ PROV_CONN }}\"
  #       nmcli connection add ifname provisioning type bridge con-name provisioning
  #       nmcli con add type bridge-slave ifname \"{{ PROV_CONN }}\" master provisioning
  #       nmcli connection modify provisioning ipv6.addresses fd00:1101::1/64 ipv6.method manual
  #       nmcli con down provisioning
  #       nmcli con up provisioning
  #   when: PROV_CONN is not 'none'

  # - name: Configure the IPv4 address on the provisioning network connection
  #   ansible.builtin.command:
  #     cmd: |
  #       nmcli connection modify provisioning ipv4.addresses 172.22.0.254/24 ipv4.method manual
  #   when: PROV_CONN is not 'none'
